### ISSUE TITLE
No password supplied

### ISSUE THREAD

**Issue by philip-jonas** [lspiehler/node-openssl-cert#1]
Hi, When generating a new CSR using a PVT key with no password I get a error:

`rivate async generatePrivateKey(wordpressInstanceId):Promise<any> {
        // TODO: change these to env variables
        var rsakeyoptions = {
                encryption: {
                    password: false,
                    cipher: 'des3'
                },
                rsa_keygen_bits: 2048,
                rsa_keygen_pubexp: 65537,
                format: 'PKCS8'
            };

        return new Promise((resolve, reject)=> {
           this.node_openssl.generateRSAPrivateKey(rsakeyoptions, async (err, key, cmd) => {
                if (!_.isEmpty(key)) {
                    this.privateKey = key;
                    let results = await this.wordpressSSLModel.upsertPrivateKey(wordpressInstanceId, key);
                    resolve(results);
                } else {
                    reject("Something went wrong");
                }
            });
        });
    }`

And the error:
`{
    "response": {
        "code": 500,
        "response": {
            "Something went wrong": "User interface error\nunable to load Private Key\n140735828341768:error:09FFF068:PEM routines:CRYPTO_internal:bad password read:pem/pem_pkey.c:119:\n"
        }
    }
}`

We idealy dont want to use a password. please advise

**Comment by philip-jonas** [comment]
Nevermind. it seems that if u set encryption with no password it defaults to a password of test123

**Comment by lspiehler** [comment]
A password must be supplied to encrypt the key. If you do not want to use a password, omit the encryption property from rsakeyoptions, like so:

var rsakeyoptions = {
    rsa_keygen_bits: 2048,
    rsa_keygen_pubexp: 65537,
    format: 'PKCS8'
};
