### ISSUE TITLE
No way to print CA cert sha-256 fingerprint.

### ISSUE THREAD

**Issue by vchan023** [lspiehler/node-openssl-cert#11]
Hi,
I see you have a command to print the certificate info and it prints the sha1 fingerprint. Can this be setup to pass the option to print sha256?

Or anyway you can set up a command to print the cert fingerprints? 
Something along the lines of:

openssl x509 -noout -fingerprint -sha256 -inform pem -in [some CA cert path]

You could also potentially pass different options instead of -sha256 such as :
-sha1
-md5

**Comment by lspiehler** [comment]
You can use the getCertHash function to get the sha256 hash. sha1 and md5 are both supported. It ultimately uses the exact command you mentioned. Here's an example:

```
fs.readFile('./cert.crt', function(err, contents) {
	openssl.getCertHash(contents.toString(), 'sha256', function(err, hash, cmd) {
		if(err) {
			console.log(err);
		} else {
			console.log(hash);
		}
	});
});
```

Output:
```
28:7A:0F:6A:ED:B9:9F:79:2D:DA:CF:39:2E:C5:27:04:05:61:52:A1:24:2D:EA:BF:DE:02:61:29:7D:A2:D5:CB
```

**Comment by vchan023** [comment]
Thanks for your quick reply! This will do.
