### ISSUE TITLE
How create a pen file

### ISSUE THREAD

**Issue by jcpc91** [lspiehler/node-openssl-cert#3]
hi 
i have two files one is a *.cer and the other is a *.key file searching in google i found i can run the command to convert the file
>openssl pkcs8 -inform DER -in private.key -out private.key.pem -passin pass:myverystrongpass

and with this command for the *.cer file
>openssl x509 -inform DER -outform PEM -in certificado.cer -pubkey > certificado.cer.pem

what i need is generate thus files with node 
thanks for the answer

**Comment by lspiehler** [comment]
Assuming you want to generate a new RSA key and create a self signed certificate, here is an example:

```
const node_openssl = require('node-openssl-cert');
const openssl = new node_openssl();

let keypassword = 'myverystrongpass';

var rsakeyoptions = {
    encryption: {
        password: keypassword,
        cipher: 'des3'
    },
    rsa_keygen_bits: 2048,
    rsa_keygen_pubexp: 65537,
    format: 'PKCS8'
}

var csroptions = {
    subject: {
        countryName: 'US',
        stateOrProvinceName: 'Louisiana',
        commonName: [
            'certificatetools.com',
            'www.certificatetools.com'
        ],
    },
    extensions: {
        keyUsage: {
            usages: [
                'digitalSignature',
                'keyEncipherment'
            ]
        },
        extendedKeyUsage: {
            usages: [
                'serverAuth',
                'clientAuth'
            ]	
        },
        SANs: {
            DNS: [
                'certificatetools.com',
                'www.certificatetools.com'
            ]
        }
    }
}

openssl.generateRSAPrivateKey(rsakeyoptions, function(err, key, cmd) {
    //this is your key.pem output, optionally write it to a file
    console.log(key);
    openssl.generateCSR(csroptions, key, keypassword, function(err, csr, cmd) {
        if(err) {
            console.log(err);
        } else {
            //csr output is here if you want it
            console.log(csr);
            csroptions.days = 10;
			openssl.selfSignCSR(csr, csroptions, key, keypassword, function(err, crt, cmd) {
                //this is your cert.pem output, optionally write it to a file
                console.log(crt)
            });
        }
            
    });
});
```

Let me know if my assumptions are wrong. The library has the ability to work with existing certificates and keys and I can provide additional examples. This was tested on [runkit](https://npm.runkit.com/node-openssl-cert).

**Comment by lspiehler** [comment]
Did you get what you needed? Let me know if I can help further or if the issue can be closed.

**Comment by jcpc91** [comment]
thanks for you support 
what im looking its sign with (if i understand) sign some documents with thus file and someone give and example in php

`$private_file="c:/firma/llave_carlos.key.pem";`
`$public_file="c:/firma/cert_carlos.cer.pem";`
`$private_key = openssl_get_privatekey(file_get_contents($private_file));`
`exito = openssl_sign($cadena_original,$Firma,$private_key, OPENSSL_ALGO_SHA256);`
`openssl_free_key($private_key);`
`$public_key = openssl_pkey_get_public(file_get_contents($public_file));`
`$PubData = openssl_pkey_get_details($public_key);`
`$result = openssl_verify($cadena_original, $Firma, $public_key, "sha256WithRSAEncryption");`

i would like to do the same in node
thanks

**Comment by lspiehler** [comment]
This library supports the creation of keys as well as creation and signing of certificate signing requests/certificates. It does not have the ability to sign documents, but it can create the keys/certificates that you would use to do so.

**Comment by jcpc91** [comment]
hi thanks for you support 
my final solution was spawned a command  
`spawn.spawn('openssl', ['pkcs8', '-inform', 'DER', '-in', keyfilepath, '-passin', pass:${passwordkey}`]);`

`spawn.spawn('openssl', ['x509', '-inform', 'DER', '-outform', 'pem', '-in', certificadofilepath, '-pubkey']);
 `
in my test works perfectly 

so what do you think?
is a good solution for a production environment?

**Comment by lspiehler** [comment]
Depends on your needs. Only testing will tell for sure : )
