### ISSUE TITLE
Configure openssl bin path

### ISSUE THREAD

**Issue by insoluzioni** [lspiehler/node-openssl-cert#4]
Maybe you could write it in the documentation, where is the system path and where you should change if the path is not that.

I'm running on Windows, and openssl defaults the installation to C:\Program Files\OpenSLL-blahblah. So it couldn't be found and was returning ENOENT.

Perhaps if you append a variable to package.json such as "opensslPath" for example, so first time users can configure it. Workaround was editing 'index.js'

**Comment by lspiehler** [comment]
Agreed. I've updated the README. I've done very little validation so the path must be specified with forward slashes. Windows users might be able to use double backslashes, but I haven't tested it. Here is an example of me using the openssl binary that ships with the windows install of OpenVPN:
```
const node_openssl = require('node-openssl-cert');

var options = {
	binpath: 'C:/Program Files/OpenVPN/bin/openssl.exe'
}

const openssl = new node_openssl(options);
```
Try it out and let me know how it goes. Thank you for your input.

**Comment by insoluzioni** [comment]
Thank you @lspiehler !! It works!!
I'm sorry, I haven't understood the "systempath" part, since I'm a Windows-born programmer... but now I get it.

Thank you again. Best regards,
