### ISSUE TITLE
Occasionally get an exception when calling CASignCSR

### ISSUE THREAD

**Issue by pipi0502** [lspiehler/node-openssl-cert#6]
I think the issue is that, when fs.readFile(..) is called for the "serialpath" file, the file is deleted before it is read and the callback subsequently throws an exception.
Solution is to place the following code:
```
fs.unlink(serialpath, function(err) {
    //delete temp serial file
});
```
inside the callback for the readFile call.

**Comment by lspiehler** [comment]
Thank you for reporting the bug. I made the change. Please test and let me know if it is working better for you.

**Comment by pipi0502** [comment]
This fixed the issue - thank you for your swift response!
