### ISSUE TITLE
CASignCSR doesn't use hash option

### ISSUE THREAD

**Issue by vchan023** [lspiehler/node-openssl-cert#7]
In the CSR options one can define the hash type as shown in your examples, such as ca_example.js, but it is never used in the CASignCSR as an option. 

For example you'd expect this command

    'openssl x509 -req -in cert.csr -days 3650 -CA ca.crt -CAkey priv.key -extfile certconfig.txt -extensions req_ext -CAserial /var/folders/t8/_109mrrd7f525_c1mm9yv_300000gn/T/tmp-16142opNrZDkqksQU -CAcreateserial -sha256 -out cert.crt'

Note -sha256 option
When setting these options are set:
csroptions = {
  days: 3650,
  hash: 'sha256',
  subject: {
		countryName: 'US',
		stateOrProvinceName: 'Florida',
		localityName: '',
		postalCode: '',
		streetAddress: '',
		organizationName: '',
		emailAddress: ',
		organizationalUnitName: [],
		commonName: []
	},
}

Instead you get something like:
   'openssl x509 -req -in cert.csr -days 3650 -CA ca.crt -CAkey priv.key -extfile certconfig.txt -extensions req_ext -CAserial /var/folders/t8/_109mrrd7f525_c1mm9yv_300000gn/T/tmp-16116VW2UxmuUH6ZN -CAcreateserial -out cert.crt'

Is there a way to force the command to use -hash256 option? I noticed it in the certconfig.txt file but the outputs of the commands are different.

**Comment by lspiehler** [comment]
I made commit this morning to fix this issue. Please test and let me know if it works for you. Thanks!
