### ISSUE TITLE
CASignCSR fails if CSR contains SAN with IPv6 address

### ISSUE THREAD

**Issue by hardillb** [lspiehler/node-openssl-cert#9]
I'm assuming this is a parsing issue because the SAN entry looks like:

```
X509v3 Subject Alternative Name: 
                DNS:localhost, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1
```
And [somewhere](https://github.com/lspiehler/node-openssl-cert/blob/master/index.js#L339) is splitting on the `:` and only using the first and second entry, rather than just trimming the first off and using the rest.

The configuration generated has `IP.1=0` rather than `IP.1=0:0:0:0:0:0:0:1`

Example CSR that should have IPv6 `::1` as a SAN entry

```
-----BEGIN CERTIFICATE REQUEST-----
MIIDDjCCAfYCAQAwVDESMBAGA1UEAwwJbG9jYWxob3N0MRAwDgYDVQQKDAdIYXJk
aWxsMQswCQYDVQQLDAJDQTESMBAGA1UECAwJSGFtcHNoaXJlMQswCQYDVQQGEwJH
QjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANI3371eBdCMQxidI1aQ
bv5UM11Rs2jo9erWWeOI2RhMqhn2S7MI4hPYiyBjdB8f1qu8sraMmeP7wtzd+LAN
mko3RJdmANvnVgnYfM8HURub1BgrYElTEbVOD0Cx/R+sn1swuZgSiqsk7VfYiGLp
JziHjFuzh+GfzIi7jg/k2pT7qoPsXpowkF+1hjkjZLmUTwKyqps8LHQPOZjpC6z4
oR5uHNi1nS0Xg35Ii7wulvS5L35LkfujWz1kb7Qf/i7I+0WbQ9OS+gzjYl895K8p
aAvfsz+SFLjVEUS0hNHQoQDMiDaKD1yt4oLsQDkDtC032tWEUVGHYBZcwbAXkDX6
CDUCAwEAAaB1MHMGCSqGSIb3DQEJDjFmMGQwDAYDVR0TAQH/BAIwADAOBgNVHQ8B
Af8EBAMCBaAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwEwLAYDVR0RBCUwI4IJbG9j
YWxob3N0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMA0GCSqGSIb3DQEBCwUAA4IB
AQCi9ZUrq7vJIEsVTLeQrGZR+yw4o71AXVrYG1I8rouCCXzhBj4PTw9K3U5UUr3j
0Hu1brgCdycv+/bAASIE/T63U6jtX8LLwodIHfL9N0X8UNkr3eDJfaXeZ+Ci6ZGm
eeXILt8PQpJtAzeXs4nVcoLTlEabZIkHBOOoWAnnsFn7KlkamPsBaWsux3o78ubw
703a+j91tG0Sv4duG6+m4LI+d+/gjAbAOjkrJkU4knZeTh/d2xzYld3J/ZMUKq74
Jw4G6g1uTRuFgh4aJcn9QHoI3dI7ME2ZGQG06U9Qick3NNtShRU7UWxXdRoJONT7
VA/XlRKW3/q+0yfvnwB0dwwj
-----END CERTIFICATE REQUEST-----

```

**Comment by hardillb** [comment]
Potential fix, starts at https://github.com/lspiehler/node-openssl-cert/blob/master/index.js#L348

```
			var value = san[1];
			if (type === "IP" && san.length > 2) {
				san.shift();
				value = san.join(":")
			}
			//console.log(type + ' - ' + value);
```

If I get some time I'll try and submit a proper PR

**Comment by lspiehler** [comment]
Thank you for catching this. I handled it a little differently than your recommendation. I committed it directly to the master branch. Please test and let me know if it's working for you now. https://github.com/lspiehler/node-openssl-cert/commit/ac50181f242129782d191798c44d6b9e7dc772f4

**Comment by hardillb** [comment]
Looks good. I was just gunning for a belt and braces approach with the if block.

**Comment by lspiehler** [comment]
I just checked out your web-ca project. If you're interested in tinkering with something similar, I'd love your feedback on one of my sites https://pkiaas.io. It supports a feature I call IoT-HSM that allows you to keep your private key on a yubikey on your network if you're uncomfortable letting the site manage it.

**Comment by hardillb** [comment]
Closing as 0.1.35 now on npmjs.org
